--- 
default: 
  adapter: mysql2
  encoding: utf8
  host: "127.0.0.1"
  password: 4kayamoses
  pool: 5
  port: 3306
  username: root
development: 
  adapter: mysql2
  database: capstone_development
  encoding: utf8
  host: "127.0.0.1"
  password: 4kayamoses
  pool: 5
  port: 3306
  username: root
production: 
  adapter: mysql2
  database: capstone_production
  encoding: utf8
  password: 4kayamoses
  username: root
test: 
  adapter: mysql2
  database: capstone_test
  encoding: utf8
  host: "127.0.0.1"
  password: 4kayamoses
  pool: 5
  port: 3306
  username: root
